version: '3'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdata1:/var/lib/mysql
    networks:
      - mynet1
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - mynet1
    build:
      context: .
      dockerfile: authenticationDBMigration.dockerfile
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
      - 5000:5000
    networks:
      - mynet1
    build:
      context: .
      dockerfile: authentication.dockerfile
  applicationsDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdata2:/var/lib/mysql
    networks:
      - mynet2
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynet2
  applicationsDBMigration:
    image: applicationsdbmigration
    environment:
      - DATABASE_URL=applicationsDB
    depends_on:
      applicationsDB:
        condition: service_healthy
    networks:
      - mynet2
    build:
      context: .
      dockerfile: applicationsDBMigrations.dockerfile
  customer:
    image: customer
    environment:
      - DATABASE_URL=applicationsDB
      - TZ=Europe/Paris
    depends_on:
      - applicationsDBMigration
    ports:
      - 5001:5001
    networks:
      - mynet2
    build:
      context: .
      dockerfile: customer.dockerfile
  warehouse:
    image: warehouse
    environment:
      - DATABASE_URL=applicationsDB
    depends_on:
      - applicationsDBMigration
    ports:
      - 5002:5002
    networks:
      - mynet2
    build:
      context: .
      dockerfile: warehouse.dockerfile
  admin:
    image: admin
    environment:
      - DATABASE_URL=applicationsDB
      - TZ=Europe/Paris
    depends_on:
      - applicationsDBMigration
    ports:
      - 5003:5003
    networks:
      - mynet2
    build:
      context: .
      dockerfile: admin.dockerfile
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=applicationsDB
      - TZ=Europe/Paris
    depends_on:
      - applicationsDBMigration
    networks:
      - mynet2
    build:
      context: .
      dockerfile: daemon.dockerfile

volumes:
  dbdata1:
  dbdata2:

networks:
  mynet1:
  mynet2:
