version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbAuthenticationData:/var/lib/mysql
    networks:
      - authentication
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    networks:
      - authentication
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    ports:
      - "5000:5000"
    networks:
      - authentication
  applicationsDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbApplicationsData:/var/lib/mysql
    networks:
      - daemon
      - customer
      - admin
  applicationsDBMigration:
    image: applicationsdbmigration
    environment:
      - DATABASE_URL=applicationsDB
    networks:
      - daemon
      - customer
      - admin
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - warehouse
      - daemon
  customer:
    image: customer
    environment:
      - DATABASE_URL=applicationsDB
      - TZ=Europe/Paris
    ports:
      - "5001:5001"
    networks:
      - customer
    deploy:
      replicas: 3
  warehouse:
    image: warehouse
    environment:
      - DATABASE_URL=applicationsDB
    ports:
      - "5002:5002"
    networks:
      - warehouse
    deploy:
      replicas: 3
  admin:
    image: admin
    environment:
      - DATABASE_URL=applicationsDB
      - TZ=Europe/Paris
    ports:
      - "5003:5003"
    networks:
      - admin
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=applicationsDB
      - TZ=Europe/Paris
    networks:
      - daemon

volumes:
  dbAuthenticationData:
  dbApplicationsData:

networks:
  authentication:
    driver: overlay
  admin:
    driver: overlay
  customer:
    driver: overlay
  warehouse:
    driver: overlay
  daemon:
    driver: overlay